// AUTO-GENERATED by scripts/generate-expected-migrations.mjs — DO NOT EDIT BY HAND.
// Regenerated in the Vercel build before `next build`. Lists the Prisma migrations
// this code expects to be applied; lib/db/migration-drift.ts compares it to the
// live DB so a lagging production database fails loud instead of breaking silently.
// (Regenerate locally with: node scripts/generate-expected-migrations.mjs)

export const EXPECTED_MIGRATIONS: readonly string[] = [
  "20260507003000_initial_backend",
  "20260510061919_add_manifest_patches",
  "20260510160000_add_classification_failure_fields",
  "20260510220000_add_proposal_product_links",
  "20260519120000_add_vendor_ranking_snapshots",
  "20260608000000_add_vendor_role_infra_fields",
  "20260619000000_add_vendor_category_change_proposals",
  "20260625000000_wave1_phase1_foundations",
  "20260626000000_phase2_member_identity",
  "20260626000001_auth_token_requester_hash",
  "20260626000002_watchlists_email_userid_drift",
  "20260626000003_add_delivery_partnership_layer",
];

/** The newest migration the code ships with (last in chronological order). */
export const LATEST_EXPECTED_MIGRATION = "20260626000003_add_delivery_partnership_layer" as const;
