// Seed vendor intelligence profiles for the 20 MVP vendors.
// Numbers are illustrative mocks (v0.2). Real ingestion replaces them.
// Aligns to the `Vendor` shape in ./types.ts.

import type { Vendor, VendorPillarScore } from "./types";

const today = "2026-05-04";

const v = (p: Vendor): Vendor => p;

export const VENDORS: Vendor[] = [
  v({
    id: "vendor_openai", name: "OpenAI", slug: "openai",
    category: "Frontier model API",
    description: "Frontier reasoning + multimodal models exposed via enterprise API and ChatGPT Enterprise.",
    headquarters: "San Francisco, USA", ownershipType: "private",
    supportedIndustries: ["enterprise_software", "commercial_enterprise", "legal_professional", "regulated_financial"],
    supportedUseCases: ["knowledge_assistant", "code_assistant", "data_analysis", "marketing_content", "sales_research"],
    supportedEcosystems: ["microsoft", "azure", "aws", "snowflake", "databricks"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 78, confidenceScore: 76, marketPosition: "leader",
    strategy: "ChatGPT Enterprise as the seat-based assistant; the API as the platform substrate; Microsoft for distribution and infra.",
    productCapabilities: ["Frontier reasoning models", "Responses + Assistants API", "Computer-use beta", "Realtime API"],
    enterpriseControls: ["No-train DPA on Enterprise", "EU residency option", "Audit logs", "SSO + RBAC"],
    agenticCapability: "Native tool-use, structured outputs, and an Assistants/Responses API; agent demos lead the field but production-grade controls still maturing.",
    industryStrength: [
      { industry: "enterprise_software", score: 86, note: "Heavy developer adoption" },
      { industry: "commercial_enterprise", score: 80, note: "Broad use-case fit" },
      { industry: "regulated_financial", score: 65, note: "Mediated via Microsoft / Azure OpenAI" },
    ],
    riskProfile: ["Microsoft / Azure infra concentration", "Pricing volatility on heavy reasoning", "SCIM maturity"],
    analystInterpretation: "Buy-and-fence in regulated workloads; lean in for productivity and developer use cases. Wins agentic compute, but commercial leverage is heavily Microsoft-shaped.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_microsoft", name: "Microsoft", slug: "microsoft",
    category: "Enterprise assistant",
    description: "Copilot ecosystem across M365, Dynamics, GitHub, Power Platform; Azure AI Foundry for custom builds.",
    headquarters: "Redmond, USA", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "public_sector_education", "health_life_sciences", "commercial_enterprise", "enterprise_software"],
    supportedUseCases: ["knowledge_assistant", "code_assistant", "operations_automation", "customer_service_agent", "data_analysis"],
    supportedEcosystems: ["microsoft", "azure"],
    deploymentOptions: ["saas", "vpc", "sovereign"], autonomyLevelMax: "supervised_agent",
    overallScore: 82, confidenceScore: 84, marketPosition: "leader",
    strategy: "Embed AI into the seat the enterprise already pays for. Copilot is the wedge; Azure AI Foundry is where the durable platform revenue lives.",
    productCapabilities: ["M365 Copilot", "GitHub Copilot", "Azure AI Foundry", "Copilot Studio", "Dynamics 365 Copilot"],
    enterpriseControls: ["Tenant isolation", "Sovereign Cloud", "EU AI Act mapping", "BYOK", "Comprehensive audit log integrations"],
    agenticCapability: "Copilot Studio + Azure AI Agent Service; behind OpenAI on raw reasoning, ahead on operationally-controlled multi-agent orchestration.",
    industryStrength: [
      { industry: "regulated_financial", score: 88, note: "Sovereign Cloud + tenant isolation" },
      { industry: "public_sector_education", score: 85, note: "Government Cloud track record" },
      { industry: "commercial_enterprise", score: 90, note: "Default M365 footprint" },
    ],
    riskProfile: ["Frontier-model dependency on OpenAI", "Copilot adoption uneven across SKUs"],
    analystInterpretation: "Default-safe choice for regulated, multi-cloud-averse enterprises. Pricing leverage shifts to Microsoft as Copilot per-seat economics compound.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_google", name: "Google", slug: "google",
    category: "Cloud AI platform",
    description: "Gemini family + Vertex AI + Workspace integration; cloud-first agentic stack with strong multimodal.",
    headquarters: "Mountain View, USA", ownershipType: "public",
    supportedIndustries: ["enterprise_software", "commercial_enterprise", "public_sector_education"],
    supportedUseCases: ["knowledge_assistant", "data_analysis", "marketing_content", "code_assistant", "customer_service_agent"],
    supportedEcosystems: ["google_workspace", "gcp"],
    deploymentOptions: ["saas", "vpc", "sovereign"], autonomyLevelMax: "supervised_agent",
    overallScore: 75, confidenceScore: 74, marketPosition: "challenger",
    strategy: "Triple-stack play across model, cloud and workspace. Gemini's long-context + multimodal is the technical edge; Workspace adoption is the commercial test.",
    productCapabilities: ["Gemini family", "Vertex AI Agent Builder", "Workspace Duet AI", "Imagen + Veo", "Notebook LM"],
    enterpriseControls: ["VPC-SC", "BYOK", "Residency", "Customer-managed keys"],
    agenticCapability: "Vertex AI Agent Builder + Gemini tool-use; competitive but ecosystem fragmentation slows enterprise rollout.",
    industryStrength: [
      { industry: "enterprise_software", score: 82, note: "Developer ecosystem on GCP" },
      { industry: "commercial_enterprise", score: 76, note: "Workspace adoption uneven" },
    ],
    riskProfile: ["Workspace adoption gating commercial leverage", "Field sales motion lags hyperscaler peers"],
    analystInterpretation: "Strong technical bet for data-intensive workloads; commercial scale depends on Workspace conversion. Watch Gemini-on-Microsoft permission stories.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_anthropic", name: "Anthropic", slug: "anthropic",
    category: "Frontier model API",
    description: "Claude family of frontier models with category-leading reasoning + safety; AWS-native distribution.",
    headquarters: "San Francisco, USA", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "legal_professional", "enterprise_software", "commercial_enterprise"],
    supportedUseCases: ["knowledge_assistant", "code_assistant", "contract_review", "data_analysis"],
    supportedEcosystems: ["aws", "gcp", "snowflake", "databricks"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 80, confidenceScore: 79, marketPosition: "leader",
    strategy: "Frontier reasoning + a deliberate enterprise-control narrative. Bedrock distribution removes procurement friction in AWS shops.",
    productCapabilities: ["Claude family models", "Computer-use", "Tool-use", "Agent SDK"],
    enterpriseControls: ["No-train DPA default", "AWS Bedrock + GCP Vertex deployment", "Audit logging"],
    agenticCapability: "Computer-use + tool-use leadership; production agentic deployments increasingly reference Claude for plan-and-act workloads.",
    industryStrength: [
      { industry: "regulated_financial", score: 78, note: "Bedrock distribution" },
      { industry: "legal_professional", score: 80, note: "Reasoning quality preferred for contract work" },
      { industry: "enterprise_software", score: 82, note: "Strong developer adoption" },
    ],
    riskProfile: ["Capital intensity of frontier training", "Hyperscaler distribution dependency"],
    analystInterpretation: "Top pick when reasoning quality and safety posture matter; pair-buy with OpenAI to avoid single-model concentration.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_aws", name: "AWS", slug: "aws",
    category: "Cloud AI platform",
    description: "Bedrock as the model marketplace + SageMaker for training/serving; Q for in-product assistant moments.",
    headquarters: "Seattle, USA", ownershipType: "subsidiary",
    supportedIndustries: ["regulated_financial", "public_sector_education", "critical_infrastructure_defence", "enterprise_software", "commercial_enterprise"],
    supportedUseCases: ["knowledge_assistant", "code_assistant", "data_analysis", "operations_automation"],
    supportedEcosystems: ["aws"],
    deploymentOptions: ["saas", "vpc", "sovereign"], autonomyLevelMax: "supervised_agent",
    overallScore: 76, confidenceScore: 80, marketPosition: "leader",
    strategy: "Multi-model marketplace via Bedrock; deep IAM/PrivateLink integration. Bet that procurement and security gravity drag AI workloads to the cloud the data already lives in.",
    productCapabilities: ["Bedrock", "Bedrock Agents", "Strands SDK", "SageMaker", "Amazon Q"],
    enterpriseControls: ["Best-in-class IAM", "KMS", "PrivateLink", "GuardDuty"],
    agenticCapability: "Bedrock Agents + Strands SDK; multi-vendor agent stories are credible and Bedrock-shaped.",
    industryStrength: [
      { industry: "critical_infrastructure_defence", score: 86, note: "GovCloud + sovereign regions" },
      { industry: "regulated_financial", score: 84, note: "Default banking cloud" },
    ],
    riskProfile: ["Q in-product assistant lags peers", "Field message confusing across Bedrock vs Q vs SageMaker"],
    analystInterpretation: "Lowest-friction path for AWS-resident enterprises. Optimise for Bedrock + Strands + your preferred frontier model rather than waiting for Q.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_salesforce", name: "Salesforce", slug: "salesforce",
    category: "CRM / customer AI",
    description: "Agentforce platform + Data Cloud + Einstein in CRM workflows; deep front-office grounding.",
    headquarters: "San Francisco, USA", ownershipType: "public",
    supportedIndustries: ["commercial_enterprise", "regulated_financial", "enterprise_software"],
    supportedUseCases: ["customer_service_agent", "sales_research", "operations_automation", "marketing_content"],
    supportedEcosystems: ["salesforce"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 71, confidenceScore: 72, marketPosition: "leader",
    strategy: "Reposition CRM as the agentic OS for the enterprise front office. Pricing model shifting from seats to consumption — a structural commercial bet.",
    productCapabilities: ["Agentforce", "Data Cloud", "Einstein Trust Layer", "Prompt Builder"],
    enterpriseControls: ["Trust Layer mediation", "PII masking", "Audit + governance"],
    agenticCapability: "Agentforce uniquely tightly coupled to the system of record; production deployments reference real customer-service deflection rates.",
    industryStrength: [
      { industry: "commercial_enterprise", score: 88, note: "CRM gravity" },
      { industry: "regulated_financial", score: 76, note: "FSC bundle adoption" },
    ],
    riskProfile: ["Per-conversation pricing friction", "Integration depth outside CRM remains shallow"],
    analystInterpretation: "Strong default for customer-service and sales agent use cases inside a Salesforce stack; weaker pick when CRM is not the system of record.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_servicenow", name: "ServiceNow", slug: "servicenow",
    category: "ITSM / HR / service AI",
    description: "Now Assist + agentic flows across IT, HR, customer service; deep workflow grounding.",
    headquarters: "Santa Clara, USA", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "public_sector_education", "commercial_enterprise", "enterprise_software"],
    supportedUseCases: ["operations_automation", "customer_service_agent", "knowledge_assistant"],
    supportedEcosystems: ["servicenow"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 74, confidenceScore: 75, marketPosition: "leader",
    strategy: "Make Now the workflow plane for AI actions. Strong land-and-expand inside existing ITSM/HR/CSM accounts.",
    productCapabilities: ["Now Assist", "AI Agents", "Workflow Studio", "Now Intelligence"],
    enterpriseControls: ["Mature audit", "Role model", "Data residency", "Workflow Studio governance"],
    agenticCapability: "AI Agents tightly bound to the ServiceNow data graph; differentiation is process completeness, not raw model quality.",
    industryStrength: [
      { industry: "regulated_financial", score: 80, note: "Mature audit" },
      { industry: "public_sector_education", score: 82, note: "Strong public-sector references" },
    ],
    riskProfile: ["AI Now packaging is steep", "Cross-vendor agent interoperability"],
    analystInterpretation: "Anchor pick when the system of work is ServiceNow; less compelling outside the Now estate.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_oracle", name: "Oracle", slug: "oracle",
    category: "Cloud AI platform",
    description: "OCI Generative AI + AI agents across Fusion apps; sovereign-cloud advantage in regulated regions.",
    headquarters: "Austin, USA", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "public_sector_education", "critical_infrastructure_defence", "health_life_sciences"],
    supportedUseCases: ["operations_automation", "data_analysis", "knowledge_assistant"],
    supportedEcosystems: ["oracle", "gcp", "azure"],
    deploymentOptions: ["saas", "vpc", "sovereign", "on_prem"], autonomyLevelMax: "supervised_agent",
    overallScore: 65, confidenceScore: 68, marketPosition: "challenger",
    strategy: "Lead with sovereign + multi-cloud regions and embed AI agents into Fusion apps. Quietly winning regulated workloads where data must stay put.",
    productCapabilities: ["OCI Generative AI", "Fusion AI Agents", "OCI Vector Search", "Select AI"],
    enterpriseControls: ["Sovereign-cloud + air-gapped deployments", "ApEx-style audit"],
    agenticCapability: "Fusion AI Agents target finance, supply chain, HCM; raw model quality lags hyperscalers but workflow grounding is competitive.",
    industryStrength: [
      { industry: "regulated_financial", score: 78, note: "Banking + insurance Fusion footprint" },
      { industry: "critical_infrastructure_defence", score: 80, note: "Sovereign / GovCloud" },
    ],
    riskProfile: ["Field ecosystem narrative still catching up", "Agent ecosystem outside Fusion is thin"],
    analystInterpretation: "Underrated for sovereign + Fusion accounts; second-look candidate where data residency is non-negotiable.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_sap", name: "SAP", slug: "sap",
    category: "Workflow automation AI",
    description: "Joule assistant + Business AI across S/4HANA Cloud, SuccessFactors, Ariba, Concur.",
    headquarters: "Walldorf, Germany", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "commercial_enterprise", "industrial_physical_ops", "public_sector_education"],
    supportedUseCases: ["operations_automation", "data_analysis", "knowledge_assistant"],
    supportedEcosystems: ["sap"],
    deploymentOptions: ["saas", "vpc", "sovereign"], autonomyLevelMax: "human_in_loop",
    overallScore: 63, confidenceScore: 70, marketPosition: "challenger",
    strategy: "Use Joule and Business AI to defend the enterprise back-office. Partner-led model strategy via Microsoft + AWS reduces capex but lengthens product cycles.",
    productCapabilities: ["Joule", "Business AI", "Generative AI Hub", "Knowledge Graph"],
    enterpriseControls: ["EU sovereignty leadership", "Mature change management"],
    agenticCapability: "Joule agents land in business processes (FI, HR, P2P); raw agentic capability is conservative on purpose.",
    industryStrength: [
      { industry: "industrial_physical_ops", score: 84, note: "S/4HANA + supply-chain depth" },
      { industry: "regulated_financial", score: 74, note: "Treasury + record-to-report grounding" },
    ],
    riskProfile: ["Innovation cadence trails hyperscalers", "Partner-dependent model strategy"],
    analystInterpretation: "Required workshop for SAP-anchored enterprises; raise expectations for predictability over raw model frontier.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_ibm", name: "IBM", slug: "ibm",
    category: "Cloud AI platform",
    description: "watsonx platform + Granite models + Concert governance; Red Hat AI for hybrid.",
    headquarters: "Armonk, USA", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "health_life_sciences", "public_sector_education", "critical_infrastructure_defence"],
    supportedUseCases: ["operations_automation", "knowledge_assistant", "data_analysis"],
    supportedEcosystems: ["aws", "azure", "gcp"],
    deploymentOptions: ["saas", "vpc", "on_prem", "sovereign", "hybrid"], autonomyLevelMax: "supervised_agent",
    overallScore: 64, confidenceScore: 69, marketPosition: "challenger",
    strategy: "Hybrid + governance-led story aimed at regulated estates. Granite open-licence models reduce vendor lock-in concerns.",
    productCapabilities: ["watsonx.ai", "Granite models", "watsonx.governance", "Concert", "Red Hat AI"],
    enterpriseControls: ["Concert lifecycle governance", "Multi-cloud + on-prem optionality"],
    agenticCapability: "Agent Lab + watsonx Orchestrate; capable but model frontier lags peers.",
    industryStrength: [
      { industry: "regulated_financial", score: 78, note: "Mainframe + governance customers" },
      { industry: "health_life_sciences", score: 76, note: "EMR partnerships" },
      { industry: "public_sector_education", score: 80, note: "Federal + sovereign deployments" },
    ],
    riskProfile: ["Brand momentum still catching product reality", "Field execution variable"],
    analystInterpretation: "Strong fit for hybrid + sovereign + governance-heavy estates; weaker for greenfield AI-first builds.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_cohere", name: "Cohere", slug: "cohere",
    category: "Frontier model API",
    description: "Enterprise-tuned Command/Aya/Embed models with focus on retrieval, multilingual, and on-prem deployability.",
    headquarters: "Toronto, Canada", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "public_sector_education", "enterprise_software"],
    supportedUseCases: ["knowledge_assistant", "data_analysis", "operations_automation"],
    supportedEcosystems: ["aws", "azure", "oracle"],
    deploymentOptions: ["saas", "vpc", "on_prem", "sovereign"], autonomyLevelMax: "human_in_loop",
    overallScore: 66, confidenceScore: 68, marketPosition: "specialist",
    strategy: "Lean into enterprise/regulated deployments where model portability and on-prem economics matter. Avoids consumer noise.",
    productCapabilities: ["Command R+", "Aya multilingual", "Embed v3", "Rerank"],
    enterpriseControls: ["Strong residency + on-prem", "Documented training-data policy", "SOC 2 + ISO 27001"],
    agenticCapability: "Command R+ tool-use is competent but lags frontier reasoning leaders.",
    industryStrength: [
      { industry: "regulated_financial", score: 70, note: "On-prem deploys with major banks" },
    ],
    riskProfile: ["Capital intensity of frontier race", "Smaller field motion than hyperscaler peers"],
    analystInterpretation: "Top pick when sovereign or on-prem deployment is mandatory and multilingual retrieval is core.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_mistral", name: "Mistral AI", slug: "mistral",
    category: "Frontier model API",
    description: "European frontier models with strong open-weight + sovereign deployment story.",
    headquarters: "Paris, France", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "public_sector_education", "critical_infrastructure_defence", "enterprise_software"],
    supportedUseCases: ["knowledge_assistant", "code_assistant", "data_analysis"],
    supportedEcosystems: ["azure", "aws", "gcp"],
    deploymentOptions: ["saas", "vpc", "on_prem", "sovereign"], autonomyLevelMax: "human_in_loop",
    overallScore: 65, confidenceScore: 66, marketPosition: "fast_mover",
    strategy: "European AI sovereignty champion; mix of open-weight community-building and enterprise platform.",
    productCapabilities: ["Mistral Large + Medium", "Mixtral open-weights", "Le Chat Enterprise", "La Plateforme"],
    enterpriseControls: ["Mature sovereign deployments", "EU-jurisdiction default"],
    agenticCapability: "Function calling + structured outputs solid; agentic stack newer than US peers.",
    industryStrength: [
      { industry: "regulated_financial", score: 72, note: "EU bank workshops" },
      { industry: "public_sector_education", score: 78, note: "EU government deployments" },
    ],
    riskProfile: ["Capital concentration in EU sovereign cloud spend", "Geopolitical narrative cuts both ways"],
    analystInterpretation: "Default consideration in EU-regulated workloads; pair with Anthropic or OpenAI for redundancy.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_glean", name: "Glean", slug: "glean",
    category: "RAG / enterprise search",
    description: "Enterprise search + work assistant with deep permission-aware connectors across SaaS estates.",
    headquarters: "Palo Alto, USA", ownershipType: "private",
    supportedIndustries: ["enterprise_software", "commercial_enterprise", "regulated_financial"],
    supportedUseCases: ["knowledge_assistant", "operations_automation"],
    supportedEcosystems: ["microsoft", "google_workspace", "salesforce", "atlassian", "servicenow"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "human_in_loop",
    overallScore: 73, confidenceScore: 76, marketPosition: "leader",
    strategy: "Win the enterprise knowledge assistant by being category-best at permission inheritance and SaaS connector breadth.",
    productCapabilities: ["Glean Search", "Glean Assistant", "Glean Agents", "Connectors framework"],
    enterpriseControls: ["Source-permission inheritance", "SCIM", "Audit logs", "EU residency"],
    agenticCapability: "Agents over the connected knowledge graph; productive in the assistant moment, lighter at multi-step actuation.",
    industryStrength: [
      { industry: "enterprise_software", score: 82, note: "Tech-company default" },
    ],
    riskProfile: ["Adjacent to hyperscaler assistants", "Defensibility is connector depth + permission semantics"],
    analystInterpretation: "Buy when M365/Google Copilot are insufficient for cross-SaaS knowledge work; bigger moat than the surface UX suggests.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_moveworks", name: "Moveworks", slug: "moveworks",
    category: "ITSM / HR / service AI",
    description: "Conversational AI for IT/HR support with strong enterprise integrations; ServiceNow-acquired.",
    headquarters: "Mountain View, USA", ownershipType: "subsidiary",
    supportedIndustries: ["enterprise_software", "commercial_enterprise", "regulated_financial"],
    supportedUseCases: ["operations_automation", "customer_service_agent", "knowledge_assistant"],
    supportedEcosystems: ["servicenow", "microsoft", "salesforce"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 68, confidenceScore: 70, marketPosition: "specialist",
    strategy: "Post-acquisition, becoming the conversational front-door of the ServiceNow agent platform.",
    productCapabilities: ["Conversational AI", "Employee Service", "Agent Studio"],
    enterpriseControls: ["Mature SOC 2/ISO posture", "ServiceNow audit + governance integration"],
    agenticCapability: "Strong on bounded IT/HR workflows; broader agentic story now anchored to ServiceNow's roadmap.",
    industryStrength: [
      { industry: "enterprise_software", score: 78, note: "Tech-company helpdesk default" },
    ],
    riskProfile: ["Strategic dependency on ServiceNow integration roadmap", "Standalone differentiation narrowing"],
    analystInterpretation: "Increasingly synonymous with ServiceNow Now Assist for conversational use cases — evaluate together.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_writer", name: "Writer", slug: "writer",
    category: "Enterprise assistant",
    description: "Generative AI platform + own Palmyra models, focused on enterprise content + knowledge work.",
    headquarters: "San Francisco, USA", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "health_life_sciences", "commercial_enterprise"],
    supportedUseCases: ["marketing_content", "knowledge_assistant", "operations_automation"],
    supportedEcosystems: ["microsoft", "google_workspace", "salesforce"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 67, confidenceScore: 68, marketPosition: "specialist",
    strategy: "Own-model + enterprise-content stack as a hedge against hyperscaler assistants. Strong sales motion in regulated marketing/comms teams.",
    productCapabilities: ["Palmyra models", "AI Studio agents", "Knowledge Graph", "Brand-safety controls"],
    enterpriseControls: ["No-train DPA", "Audit logs", "HITRUST in regulated verticals"],
    agenticCapability: "AI Studio agents centre on content workflows; strong governance story for marketing risk.",
    industryStrength: [
      { industry: "regulated_financial", score: 72, note: "Regulated marketing comms" },
      { industry: "health_life_sciences", score: 76, note: "Pharma med-comms" },
    ],
    riskProfile: ["Capital intensity of own-model strategy", "Differentiation may compress as Copilot/Workspace mature"],
    analystInterpretation: "Strong pick where regulated brand safety and content governance dominate; less so when Copilot is already enough.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_hebbia", name: "Hebbia", slug: "hebbia",
    category: "Regulated-industry AI",
    description: "Matrix workflow product for analyst-grade work in finance, law, consulting; document-grounded reasoning.",
    headquarters: "New York, USA", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "legal_professional"],
    supportedUseCases: ["financial_analysis", "contract_review", "data_analysis"],
    supportedEcosystems: ["microsoft"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "human_in_loop",
    overallScore: 70, confidenceScore: 71, marketPosition: "fast_mover",
    strategy: "Productise analyst workflows. The Matrix UX bets on structured reasoning over chat as the primitive for financial + legal work.",
    productCapabilities: ["Matrix workflow", "Multi-model orchestration", "Document grounding"],
    enterpriseControls: ["Tight permissioning", "Audit", "No-train default"],
    agenticCapability: "Plan-and-act over document corpora; conservative agentic posture appropriate for the audience.",
    industryStrength: [
      { industry: "regulated_financial", score: 84, note: "Tier-1 asset-management deployments" },
    ],
    riskProfile: ["Concentration in financial vertical", "Pricing comparable to bespoke analyst headcount"],
    analystInterpretation: "Top pick for asset-management + advisory firms doing structured document work; weaker outside that lane.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_rogo", name: "Rogo", slug: "rogo",
    category: "Regulated-industry AI",
    description: "AI analyst for financial services with focus on investment banking and asset management workflows.",
    headquarters: "New York, USA", ownershipType: "private",
    supportedIndustries: ["regulated_financial"],
    supportedUseCases: ["financial_analysis", "data_analysis"],
    supportedEcosystems: ["microsoft"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "human_in_loop",
    overallScore: 66, confidenceScore: 64, marketPosition: "fast_mover",
    strategy: "Bank-grade analyst copilot with deep integration to data rooms, market data, and the bank's research stack.",
    productCapabilities: ["Pitch automation", "Comparable analysis", "Model checks"],
    enterpriseControls: ["SOC 2 Type II + bank-aligned controls"],
    agenticCapability: "Bounded agent flows for pitch creation, comps, model checks; deliberately not autonomous.",
    industryStrength: [
      { industry: "regulated_financial", score: 74, note: "IB + buy-side pilots" },
    ],
    riskProfile: ["Single-vertical concentration", "Capital resilience under scrutiny"],
    analystInterpretation: "Watchlist candidate for IB + asset-management buyers; benchmark against Hebbia + open-source workflows.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_harvey", name: "Harvey", slug: "harvey",
    category: "Regulated-industry AI",
    description: "Legal AI workflows for AmLaw 100 firms and in-house teams; deep matter/client permissioning.",
    headquarters: "San Francisco, USA", ownershipType: "private",
    supportedIndustries: ["legal_professional", "regulated_financial"],
    supportedUseCases: ["contract_review", "knowledge_assistant"],
    supportedEcosystems: ["microsoft"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "human_in_loop",
    overallScore: 79, confidenceScore: 81, marketPosition: "leader",
    strategy: "Vertical leader in legal AI; deep iManage/NetDocuments integration and rigorous citation discipline.",
    productCapabilities: ["Vault", "Workflow Builder", "Citator", "Drafting agents"],
    enterpriseControls: ["Matter/client-level data isolation", "SOC 2 Type II", "AmLaw 100 production deployments"],
    agenticCapability: "Conservative human-in-loop posture; agent assist on drafting, due diligence, research.",
    industryStrength: [
      { industry: "legal_professional", score: 92, note: "AmLaw 100 saturation" },
    ],
    riskProfile: ["Pricing comparable to senior associate headcount", "Renewal cycle scrutinises ROI rigorously"],
    analystInterpretation: "Default best-in-class for legal vertical; pair-buy with general assistant for non-legal workloads.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_databricks", name: "Databricks", slug: "databricks",
    category: "Data / analytics AI",
    description: "Data Intelligence Platform + Mosaic AI; agent + RAG over the lakehouse.",
    headquarters: "San Francisco, USA", ownershipType: "private",
    supportedIndustries: ["regulated_financial", "commercial_enterprise", "enterprise_software", "industrial_physical_ops"],
    supportedUseCases: ["data_analysis", "operations_automation", "knowledge_assistant"],
    supportedEcosystems: ["aws", "azure", "gcp", "databricks"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "supervised_agent",
    overallScore: 76, confidenceScore: 77, marketPosition: "leader",
    strategy: "Compete on data-grounded AI: Unity Catalog + Mosaic AI + Genie. Bet that AI quality follows data governance.",
    productCapabilities: ["Mosaic AI", "Unity Catalog", "Vector Search", "Genie Spaces", "Agent Framework"],
    enterpriseControls: ["Unity Catalog governance + lineage", "Mature multi-cloud control plane"],
    agenticCapability: "Mosaic AI Agent Framework + Vector Search + Genie Spaces; strong for analytics agents.",
    industryStrength: [
      { industry: "regulated_financial", score: 80, note: "Bank lakehouse deployments" },
    ],
    riskProfile: ["Hyperscaler-channel competition with native AI", "Capital-intensive multi-cloud strategy"],
    analystInterpretation: "Anchor for data + AI work where governance matters; weaker where the workload is content-only.",
    lastUpdated: today,
  }),
  v({
    id: "vendor_snowflake", name: "Snowflake", slug: "snowflake",
    category: "Data / analytics AI",
    description: "Cortex AI + Cortex Agents inside the data cloud; Snowpark Container Services for custom AI.",
    headquarters: "Bozeman, USA", ownershipType: "public",
    supportedIndustries: ["regulated_financial", "commercial_enterprise", "enterprise_software", "health_life_sciences"],
    supportedUseCases: ["data_analysis", "operations_automation"],
    supportedEcosystems: ["aws", "azure", "gcp", "snowflake"],
    deploymentOptions: ["saas", "vpc"], autonomyLevelMax: "human_in_loop",
    overallScore: 73, confidenceScore: 75, marketPosition: "challenger",
    strategy: "Win the data + AI workload by collapsing it inside the warehouse boundary. Cortex Agents are a structural bet on data-resident AI.",
    productCapabilities: ["Cortex Agents", "Cortex Search", "Cortex Analyst", "Snowpark Container Services"],
    enterpriseControls: ["Mature data governance + RBAC", "Cortex Guard for prompt-injection"],
    agenticCapability: "Cortex Agents + Cortex Search; agent surface area smaller than Databricks but governance is tight.",
    industryStrength: [
      { industry: "regulated_financial", score: 80, note: "Financial-services warehouse footprint" },
    ],
    riskProfile: ["Pricing model evolution as AI consumption grows", "Agent ecosystem still catching Databricks"],
    analystInterpretation: "Strong default for data-resident agentic workloads inside Snowflake; pair with frontier model for raw reasoning.",
    lastUpdated: today,
  }),
];

// ─── Pillar capability summaries (compact mocks for top vendors) ──────────

const pp = (
  vendorId: string, pillar: VendorPillarScore["pillar"], capabilityScore: number,
  evidenceGrade: VendorPillarScore["evidenceGrade"], confidence: number,
  strengths: string[], risks: string[], missingEvidence: string[] = [],
): VendorPillarScore => ({ vendorId, pillar, capabilityScore, evidenceGrade, confidence, strengths, risks, missingEvidence });

export const PILLAR_SCORES: VendorPillarScore[] = [
  pp("vendor_openai", "business_fit", 82, "E4", 80, ["Broad use-case fit", "Frontier reasoning"], ["Pricing volatility on heavy reasoning"]),
  pp("vendor_openai", "enterprise_control", 70, "E3", 72, ["Enterprise no-train DPA", "EU residency"], ["SCIM maturity", "Source-permission inheritance"]),
  pp("vendor_openai", "reliability_safety", 78, "E4", 78, ["Top-tier reasoning benchmarks"], ["Hallucinations on long-tail facts"]),
  pp("vendor_openai", "integration_ops", 80, "E4", 82, ["Mature SDKs", "Tool-use quality"], ["Cost at 3x usage"]),
  pp("vendor_openai", "vendor_resilience", 70, "E3", 70, ["Strong commercial momentum"], ["Microsoft / Azure dependency"]),
  pp("vendor_openai", "market_strength", 90, "E5", 88, ["Category share lead"], []),

  pp("vendor_microsoft", "business_fit", 86, "E5", 90, ["Embedded in M365 + GitHub + Dynamics"], []),
  pp("vendor_microsoft", "enterprise_control", 92, "E5", 92, ["Sovereign cloud", "Mature audit + governance"], []),
  pp("vendor_microsoft", "reliability_safety", 76, "E4", 80, ["Foundry safety filters"], ["Variability across Copilot SKUs"]),
  pp("vendor_microsoft", "integration_ops", 88, "E5", 88, ["Comprehensive ecosystem"], []),
  pp("vendor_microsoft", "vendor_resilience", 92, "E5", 92, ["Public-company financial strength"], []),
  pp("vendor_microsoft", "market_strength", 92, "E5", 92, ["Category share lead in enterprise assistant"], []),

  pp("vendor_anthropic", "business_fit", 80, "E4", 80, ["Frontier reasoning", "Strong agentic posture"], []),
  pp("vendor_anthropic", "enterprise_control", 80, "E4", 80, ["Strong DPA + AWS Bedrock + GCP Vertex"], ["SCIM maturity"]),
  pp("vendor_anthropic", "reliability_safety", 88, "E5", 88, ["Top reasoning + safety benchmarks"], []),
  pp("vendor_anthropic", "integration_ops", 82, "E4", 82, ["Bedrock + Vertex distribution"], []),
  pp("vendor_anthropic", "vendor_resilience", 70, "E3", 70, ["Diversified hyperscaler distribution"], ["Capital intensity"]),
  pp("vendor_anthropic", "market_strength", 84, "E4", 84, ["Strong growth signals"], []),

  pp("vendor_harvey", "business_fit", 90, "E5", 90, ["Legal vertical fit + AmLaw references"], ["Limited outside legal"]),
  pp("vendor_harvey", "enterprise_control", 86, "E4", 86, ["Matter/client permissioning"], []),
  pp("vendor_harvey", "reliability_safety", 92, "E5", 92, ["Citation discipline"], []),
  pp("vendor_harvey", "integration_ops", 75, "E3", 75, ["iManage + NetDocuments"], []),
  pp("vendor_harvey", "vendor_resilience", 70, "E3", 70, ["Series E"], []),
  pp("vendor_harvey", "market_strength", 80, "E4", 80, ["Legal AI category leader"], []),
];

export function getVendorIntel(slugOrId: string): Vendor | undefined {
  return VENDORS.find((v) => v.slug === slugOrId || v.id === slugOrId);
}
