// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/data-sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data-sources">> = Specific
  const handler = {} as typeof import("../../../app/admin/data-sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/evidence/batch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/evidence/batch">> = Specific
  const handler = {} as typeof import("../../../app/admin/evidence/batch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/evidence">> = Specific
  const handler = {} as typeof import("../../../app/admin/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/exposure-edits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/exposure-edits">> = Specific
  const handler = {} as typeof import("../../../app/admin/exposure-edits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/ingestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ingestion">> = Specific
  const handler = {} as typeof import("../../../app/admin/ingestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/pipeline-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pipeline-health">> = Specific
  const handler = {} as typeof import("../../../app/admin/pipeline-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/production-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/production-status">> = Specific
  const handler = {} as typeof import("../../../app/admin/production-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/assess/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assess">> = Specific
  const handler = {} as typeof import("../../../app/assess/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessment">> = Specific
  const handler = {} as typeof import("../../../app/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/atlas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/atlas">> = Specific
  const handler = {} as typeof import("../../../app/atlas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/briefings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefings">> = Specific
  const handler = {} as typeof import("../../../app/briefings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/capabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/capabilities">> = Specific
  const handler = {} as typeof import("../../../app/capabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demonstrate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demonstrate">> = Specific
  const handler = {} as typeof import("../../../app/demonstrate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/exposure-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exposure-map">> = Specific
  const handler = {} as typeof import("../../../app/exposure-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/briefing 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/briefing 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/briefing 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/briefing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/briefing">> = Specific
  const handler = {} as typeof import("../../../app/investing/briefing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/exposure-map 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/exposure-map 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/exposure-map 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/exposure-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/exposure-map">> = Specific
  const handler = {} as typeof import("../../../app/investing/exposure-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/ipo-watch 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/ipo-watch 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/ipo-watch 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/ipo-watch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/ipo-watch">> = Specific
  const handler = {} as typeof import("../../../app/investing/ipo-watch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing">> = Specific
  const handler = {} as typeof import("../../../app/investing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/provider 2/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/provider 2/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/investing/provider 2/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/provider/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/provider/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/investing/provider/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/public 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/public 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/public 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/public/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/public">> = Specific
  const handler = {} as typeof import("../../../app/investing/public/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/simulator 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/simulator 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/simulator 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/simulator">> = Specific
  const handler = {} as typeof import("../../../app/investing/simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/watchlist 2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/watchlist 2">> = Specific
  const handler = {} as typeof import("../../../app/investing/watchlist 2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investing/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investing/watchlist">> = Specific
  const handler = {} as typeof import("../../../app/investing/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/briefing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/briefing">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/briefing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/briefings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/briefings">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/briefings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/exposure-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/exposure-map">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/exposure-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/intelligence">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/ipo-watch/[providerSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/ipo-watch/[providerSlug]">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/ipo-watch/[providerSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/ipo-watch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/ipo-watch">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/ipo-watch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/provider/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/provider/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/provider/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/public/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/public">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/public/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/signals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/signals">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/signals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/simulator">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/investor-tools/watchlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor-tools/watchlist">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/watchlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/market">> = Specific
  const handler = {} as typeof import("../../../app/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/methodology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/methodology">> = Specific
  const handler = {} as typeof import("../../../app/methodology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../../app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/quadrant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quadrant">> = Specific
  const handler = {} as typeof import("../../../app/quadrant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/query-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/query-v2">> = Specific
  const handler = {} as typeof import("../../../app/query-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/query/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/query">> = Specific
  const handler = {} as typeof import("../../../app/query/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reputation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reputation">> = Specific
  const handler = {} as typeof import("../../../app/reputation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/results/[runId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results/[runId]">> = Specific
  const handler = {} as typeof import("../../../app/results/[runId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/understand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/understand">> = Specific
  const handler = {} as typeof import("../../../app/understand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/vendors/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/vendors/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendors">> = Specific
  const handler = {} as typeof import("../../../app/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/watchlists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/watchlists">> = Specific
  const handler = {} as typeof import("../../../app/watchlists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/apply-linkages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/apply-linkages">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/apply-linkages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/batch-action/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/batch-action/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/batch-action/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/batch-action/ids/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/batch-action/ids">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/batch-action/ids/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/dedup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/dedup">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/dedup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/failures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/failures">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/failures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/linkage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/linkage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/linkage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/evidence/triage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/evidence/triage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/evidence/triage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/exposure-edits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/exposure-edits">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/exposure-edits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ingestion/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ingestion/jobs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ingestion/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/ingestion/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ingestion/run">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/ingestion/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/intelligence/recompute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/intelligence/recompute">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/intelligence/recompute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/production-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/production-status">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/production-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/proposals/[id]/linkage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/proposals/[id]/linkage">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/proposals/[id]/linkage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/proposals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/proposals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/proposals">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sourcing/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sourcing/logs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sourcing/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sourcing/manifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sourcing/manifest">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sourcing/manifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sourcing/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sourcing/run">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sourcing/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/assessment/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/[id]/export">> = Specific
  const handler = {} as typeof import("../../../app/api/assessment/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/assessment/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/assessment/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/assessment/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/score">> = Specific
  const handler = {} as typeof import("../../../app/api/assessment/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/briefings/weekly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/briefings/weekly">> = Specific
  const handler = {} as typeof import("../../../app/api/briefings/weekly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/capabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capabilities">> = Specific
  const handler = {} as typeof import("../../../app/api/capabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/competitive-intel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/competitive-intel">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/competitive-intel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/daily-refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/daily-refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/ranking-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/ranking-snapshot">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/ranking-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/safe-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/safe-actions">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/safe-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/sourcing-rolling/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sourcing-rolling">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/sourcing-rolling/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/[connectorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/[connectorId]">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/[connectorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/eia/retail-sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/eia/retail-sales">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/eia/retail-sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/sec/[cik]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/sec/[cik]">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/sec/[cik]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/status">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-sources/vendor-docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-sources/vendor-docs">> = Specific
  const handler = {} as typeof import("../../../app/api/data-sources/vendor-docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/demo/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo/status">> = Specific
  const handler = {} as typeof import("../../../app/api/demo/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/evidence/claims/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/claims">> = Specific
  const handler = {} as typeof import("../../../app/api/evidence/claims/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/evidence/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/sources">> = Specific
  const handler = {} as typeof import("../../../app/api/evidence/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/evidence/validate-claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/validate-claim">> = Specific
  const handler = {} as typeof import("../../../app/api/evidence/validate-claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/apply-shock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/apply-shock">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/apply-shock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/briefing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/briefing">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/briefing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/exposure-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/exposure-map">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/exposure-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/ipo-watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/ipo-watch">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/ipo-watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/providers/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/providers/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/providers/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/public">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/recalculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/recalculate">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/recalculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/save-simulation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/save-simulation">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/save-simulation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/scores">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/seed-portfolio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/seed-portfolio">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/seed-portfolio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/simulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/simulate">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/simulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investing/simulations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investing/simulations/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/investing/simulations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/briefing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/briefing">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/briefing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/briefings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/briefings">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/briefings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/exposure-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/exposure-map">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/exposure-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/intelligence">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/ipo-watch/[providerSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/ipo-watch/[providerSlug]">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/ipo-watch/[providerSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/ipo-watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/ipo-watch">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/ipo-watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/nav/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/nav">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/nav/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/product-scope/[vendorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/product-scope/[vendorId]">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/product-scope/[vendorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/product-scope/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/product-scope">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/product-scope/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/products">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/providers/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/providers/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/providers/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/public">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/scores">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/apply-random-shock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/apply-random-shock">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/apply-random-shock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/apply-shock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/apply-shock">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/apply-shock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/eligible-universe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/eligible-universe">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/eligible-universe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/exposure-network/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/exposure-network">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/exposure-network/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/filter-universe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/filter-universe">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/filter-universe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/save">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/scatter-domain/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/scatter-domain">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/scatter-domain/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/simulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/simulate">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/simulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/tooltips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/tooltips">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/tooltips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/validate-cross-feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/validate-cross-feed">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/validate-cross-feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/investor-tools/simulator/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/investor-tools/simulator/validate">> = Specific
  const handler = {} as typeof import("../../../app/api/investor-tools/simulator/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/market-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-dashboard">> = Specific
  const handler = {} as typeof import("../../../app/api/market-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/metadata">> = Specific
  const handler = {} as typeof import("../../../app/api/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/model-inventory/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/model-inventory/refresh">> = Specific
  const handler = {} as typeof import("../../../app/api/model-inventory/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/model-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/model-inventory">> = Specific
  const handler = {} as typeof import("../../../app/api/model-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/model-inventory/sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/model-inventory/sources">> = Specific
  const handler = {} as typeof import("../../../app/api/model-inventory/sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/model-inventory/vendors/[vendorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/model-inventory/vendors/[vendorId]">> = Specific
  const handler = {} as typeof import("../../../app/api/model-inventory/vendors/[vendorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/model-inventory/vendors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/model-inventory/vendors">> = Specific
  const handler = {} as typeof import("../../../app/api/model-inventory/vendors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news">> = Specific
  const handler = {} as typeof import("../../../app/api/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/rank/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rank">> = Specific
  const handler = {} as typeof import("../../../app/api/rank/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/system/last-refreshed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/last-refreshed">> = Specific
  const handler = {} as typeof import("../../../app/api/system/last-refreshed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/system/refresh-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system/refresh-history">> = Specific
  const handler = {} as typeof import("../../../app/api/system/refresh-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/claims/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/claims/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/claims/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/claims/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/claims">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/claims/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/flag-unsupported/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/flag-unsupported">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/flag-unsupported/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/refresh-required/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/refresh-required">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/refresh-required/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/stale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/stale">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/stale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/truth/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/truth/validate">> = Specific
  const handler = {} as typeof import("../../../app/api/truth/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/vendor/[id]/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/[id]/evidence">> = Specific
  const handler = {} as typeof import("../../../app/api/vendor/[id]/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/vendor/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendor/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/vendor/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/vendors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/vendors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/vendors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vendors">> = Specific
  const handler = {} as typeof import("../../../app/api/vendors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/watchlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/watchlists">> = Specific
  const handler = {} as typeof import("../../../app/api/watchlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/investor-tools/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/investor-tools">> = Specific
  const handler = {} as typeof import("../../../app/investor-tools/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
