// Board Pack Export — Pack 04.
// ─────────────────────────────
// Generates a structured board pack payload from the Demonstrate
// page data. MVP outputs Markdown; PDF/PPTX generation is roadmapped.

import type {
  BoardAssumption,
  BusinessCase,
  CompetitorProfile,
  EnterpriseRisk,
  KPI,
} from "../decision-intelligence/types";
import { SCORE_METHODOLOGIES } from "../evidence/methodology";

export interface BoardPackPayload {
  title: string;
  generatedAt: string;
  organisation?: string;
  preparedFor?: string;
  confidentiality: string;
  recommendation: string;
  cioConfidenceScore: number;
  boardDefenceScore: number;
  executiveSummary: string[];
  businessCase: BusinessCase;
  costOfInaction: string[];
  vendors: { name: string; role: string; score: number; confidence: number; topPillars: string[]; risks: string[] }[];
  competitors: CompetitorProfile[];
  risks: EnterpriseRisk[];
  mitigations: { control: string; description: string; status: string }[];
  assumptions: BoardAssumption[];
  kpis: KPI[];
  methodology: string[];
  evidenceAppendix: { claim: string; source: string; grade: string; confidence: number; date: string }[];
}

/** Render a board pack payload as Markdown. */
export function renderBoardPackMarkdown(pack: BoardPackPayload): string {
  const lines: string[] = [];
  const h1 = (t: string) => lines.push(`\n# ${t}\n`);
  const h2 = (t: string) => lines.push(`\n## ${t}\n`);
  const h3 = (t: string) => lines.push(`\n### ${t}\n`);
  const p = (t: string) => lines.push(`${t}\n`);
  const li = (t: string) => lines.push(`- ${t}`);

  h1(pack.title);
  p(`**Generated:** ${new Date(pack.generatedAt).toLocaleDateString()}`);
  if (pack.organisation) p(`**Organisation:** ${pack.organisation}`);
  if (pack.preparedFor) p(`**Prepared for:** ${pack.preparedFor}`);
  p(`**Confidentiality:** ${pack.confidentiality}`);
  p(`---`);

  h2("Executive Summary");
  pack.executiveSummary.forEach((s) => li(s));
  p("");
  p(`**Recommendation:** ${pack.recommendation}`);
  p(`**CIO Confidence Score:** ${pack.cioConfidenceScore}/100`);
  p(`**Board Defence Score:** ${pack.boardDefenceScore}/100`);

  h2("Why Invest?");
  p(pack.businessCase.businessProblem);
  h3("Intended Outcomes");
  pack.businessCase.intendedOutcomes.forEach((o) => li(o));
  p(`\n**Productivity:** ${pack.businessCase.productivityImpact}`);
  p(`**Cost Reduction:** ${pack.businessCase.costReductionPotential}`);
  p(`**Revenue:** ${pack.businessCase.revenuePotential}`);

  h2("Why Now?");
  pack.costOfInaction.forEach((c) => li(c));

  h2("Recommended Vendor Shortlist");
  for (const v of pack.vendors) {
    h3(v.name);
    p(`**Role:** ${v.role} | **Score:** ${v.score} | **Confidence:** ${v.confidence}`);
    p(`**Top pillars:** ${v.topPillars.join(", ")}`);
    p(`**Risks:** ${v.risks.join(", ")}`);
  }

  h2("Competitive Position");
  for (const c of pack.competitors) {
    h3(c.peer);
    p(`**Maturity:** ${c.maturity} | **Use cases:** ${c.useCases.join(", ")}`);
    p(`**Known vendors:** ${c.knownVendors.join(", ")}`);
    p(`**CIO implication:** ${c.implication}`);
  }

  h2("Risk Register");
  lines.push("| Risk | Category | Severity | Likelihood | Mitigation | Owner |");
  lines.push("|---|---|---|---|---|---|");
  for (const r of pack.risks) {
    lines.push(`| ${r.risk} | ${r.category} | ${r.severity} | ${r.likelihood} | ${r.mitigation} | ${r.owner} |`);
  }

  h2("Controls & Governance");
  for (const m of pack.mitigations) {
    li(`**${m.control}** (${m.status}): ${m.description}`);
  }

  h2("Assumptions");
  for (const a of pack.assumptions) {
    h3(a.title);
    p(`**Status:** ${a.status} | **Confidence:** ${a.confidence}%`);
    p(`**Failure trigger:** ${a.failureTrigger}`);
    p(`**Current signal:** ${a.currentSignal}`);
    p(`**Action:** ${a.recommendedAction}`);
  }

  h2("Value Realisation KPIs");
  lines.push("| Metric | Baseline | Target | Owner | Cadence |");
  lines.push("|---|---|---|---|---|");
  for (const k of pack.kpis) {
    lines.push(`| ${k.metric} | ${k.baseline} | ${k.target} | ${k.owner} | ${k.cadence} |`);
  }

  h2("Methodology Appendix");
  for (const m of SCORE_METHODOLOGIES) {
    h3(m.name);
    p(`${m.description}`);
    p(`**Formula:** \`${m.formula}\``);
    p(`**Version:** ${m.version}`);
  }

  h2("Evidence Appendix");
  lines.push("| Claim | Source | Grade | Confidence | Date |");
  lines.push("|---|---|---|---|---|");
  for (const e of pack.evidenceAppendix) {
    lines.push(`| ${e.claim} | ${e.source} | ${e.grade} | ${e.confidence}% | ${e.date} |`);
  }

  p(`\n---`);
  p(`*Generated by AI Enterprise — AnalystGenius proprietary methodology. Estimated data is clearly labelled. Not financial, legal, or procurement advice.*`);

  return lines.join("\n");
}
